export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const INIT_COURSE = 'INIT_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_COURSE_EDIT = 'UPDATE_COURSE_EDIT';


export const FETCH_COURSE = 'FETCH_COURSE';
export const FETCH_COURSES = 'FETCH_COURSES';

export const FETCH_COURSES_BY_CREATOR = 'FETCH_COURSES_BY_CREATOR ';
export const FETCH_COURSES_BY_LEARNER = 'FETCH_COURSES_BY_LEARNER';


export const UPDATE_LAST_CHANGE = 'UPDATE_LAST_CHANGE';
export const UPDATE_TEACHERS_LAST_CHANGE = 'UPDATE_TEACHERS_LAST_CHANGE';

export const FETCH_STATUS = 'FETCH_STATUS';